import numpy as np
import matplotlib.pyplot as plt
x = np.array([0, 2, 4, 6, 9, 11, 12, 15, 17, 19])
y = np.array([5, 7, 6, 9, 8, 10, 12, 13, 17, 20])
a1, a0 = np.polyfit(x, y, 1)
y_ajustado = a0 + a1*x
r = np.corrcoef(x, y)[0,1]
Syx = np.sqrt(np.sum((y - y_ajustado)**2)/(len(x)-2))
print("Regressão de y em função de x")
print(f"Inclinação = {a1:.4f}")
print(f"Intercepto = {a0:.4f}")
print(f"Equação: y = {a0:.4f} + {a1:.4f}x")
print(f"Coeficiente de correlação (r) = {r:.4f}")
print(f"Erro padrão da estimativa = {Syx:.4f}")
plt.scatter(x, y, label="Dados")
plt.plot(x, y_ajustado, color="red", label="Reta ajustada")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid()
plt.show()
b1, b0 = np.polyfit(y, x, 1)
x_ajustado = b0 + b1*y
print("\nRegressão de x em função de y")
print(f"Inclinação = {b1:.4f}")
print(f"Intercepto = {b0:.4f}")
print(f"Equação: x = {b0:.4f} + {b1:.4f}y")
plt.scatter(y, x, label="Dados")
plt.plot(y, x_ajustado, color="red", label="Reta ajustada")
plt.xlabel("y")
plt.ylabel("x")
plt.legend()
plt.grid()
plt.show()